/**
 * Types mirroring itch's own definitions.
 *
 * Game/Upload/Build/User follow `github.com/itchio/go-itchio`, and the verdict
 * types follow `github.com/itchio/dash`. String enums are modelled as open
 * unions (`| (string & {})`) so an itch.io value this library predates still
 * type-checks.
 *
 * @module
 */

/** Any string, while still autocompleting the known values. */
type OpenEnum<T extends string> = T | (string & {});

/** `"all"`, `"386"` or `"amd64"`. */
export type IItchArchitectures = OpenEnum<"all" | "386" | "amd64">;

/** Which OS/architectures a game or upload is compatible with. */
export interface IItchPlatforms {
  windows?: IItchArchitectures;
  linux?: IItchArchitectures;
  osx?: IItchArchitectures;
}

/** How an itch.io game page is presented on the web. */
export type IItchGameType = OpenEnum<"default" | "flash" | "unity" | "java" | "html">;

/** What an itch.io page actually contains. */
export type IItchGameClassification = OpenEnum<
  | "game"
  | "tool"
  | "assets"
  | "game_mod"
  | "physical_game"
  | "soundtrack"
  | "other"
  | "comic"
  | "book"
>;

/** A game as itch describes it, shared by butler.db and on-disk receipts. */
export interface IItchGame {
  /** Site-wide unique identifier generated by itch.io. */
  id: number;
  /** Canonical address of the game's page on itch.io. */
  url?: string;
  title?: string;
  shortText?: string;
  type?: IItchGameType;
  classification?: IItchGameClassification;
  /** Cover url, which may be a GIF. */
  coverUrl?: string;
  /** Non-gif cover url, only set when the main cover is a GIF. */
  stillCoverUrl?: string;
  createdAt?: string;
  publishedAt?: string;
  /** Price in cents. */
  minPrice?: number;
  canBeBought?: boolean;
  hasDemo?: boolean;
  inPressSystem?: boolean;
  platforms?: IItchPlatforms;
  user?: IItchUser;
  userId?: number;
}

/** The itch.io account a game belongs to. */
export interface IItchUser {
  id?: number;
  username?: string;
  displayName?: string;
  developer?: boolean;
  pressUser?: boolean;
  url?: string;
  coverUrl?: string;
  stillCoverUrl?: string;
}

/** Where an upload's file is stored. */
export type IItchUploadStorage = OpenEnum<"hosted" | "build" | "external">;

/** What is in an upload. */
export type IItchUploadType = OpenEnum<
  | "default"
  | "flash"
  | "unity"
  | "java"
  | "html"
  | "soundtrack"
  | "book"
  | "video"
  | "documentation"
  | "mod"
  | "audio_assets"
  | "graphical_assets"
  | "sourcecode"
  | "other"
>;

/** The specific file/channel that was installed. */
export interface IItchUpload {
  id: number;
  storage?: IItchUploadStorage;
  /** Only set for `external` storage. */
  host?: string;
  /** Original file name, e.g. `Overland_x64.zip`. */
  filename?: string;
  /** Name set by the developer, e.g. `Overland for Windows 64-bit`. */
  displayName?: string;
  /** Size in bytes; for wharf uploads this is the archive size. */
  size?: number;
  /** Set only for wharf (butler-pushed) uploads. */
  channelName?: string;
  buildId?: number;
  build?: IItchBuild;
  type?: IItchUploadType;
  preorder?: boolean;
  demo?: boolean;
  platforms?: IItchPlatforms;
  createdAt?: string;
  updatedAt?: string;
}

/** Present only for wharf (`storage: "build"`) uploads. */
export interface IItchBuild {
  id: number;
  parentBuildId?: number;
  state?: OpenEnum<"started" | "processing" | "completed" | "failed">;
  /** Monotonic build number assigned by itch.io. */
  version?: number;
  /** The developer's own version string, e.g. `1.6.0`. */
  userVersion?: string;
  uploadId?: number;
  gameId?: number;
  userId?: number;
  createdAt?: string;
  updatedAt?: string;
}

/** The kind of a launch candidate, from `github.com/itchio/dash`. */
export type IItchFlavor = OpenEnum<
  | "linux"
  | "macos"
  | "windows"
  | "app-macos"
  | "script"
  | "windows-script"
  | "jar"
  | "html"
  | "love"
  | "msi"
>;

/** The architecture of an executable. */
export type IItchArch = OpenEnum<"386" | "amd64">;

/** Which kind of Windows installer an executable is, when it is one. */
export type IItchWindowsInstallerType = OpenEnum<"msi" | "inno" | "nsis" | "archive">;

/** Details of a native Windows executable or installer candidate. */
export interface IItchWindowsInfo {
  installerType?: IItchWindowsInstallerType;
  /** True if this looks like an uninstaller rather than an installer. */
  uninstaller?: boolean;
  /** Marked as a GUI subsystem binary. A hint, not a guarantee. */
  gui?: boolean;
  dotNet?: boolean;
}

/** Details of a native macOS candidate. Currently empty. */
export interface IItchMacosInfo {}

/** Details of a native Linux candidate. Currently empty. */
export interface IItchLinuxInfo {}

/** Details of a Love2D bundle candidate. */
export interface IItchLoveInfo {
  /** The love2d version required to open the bundle. */
  version?: string;
}

/** Details of a shell script candidate. */
export interface IItchScriptInfo {
  /** The interpreter from the shebang, e.g. `/bin/bash`. */
  interpreter?: string;
}

/** Details of a Java archive candidate. */
export interface IItchJarInfo {
  /** The `Main-Class` from the jar's manifest. */
  mainClass?: string;
}

/**
 * A launchable target butler found while scanning an install folder.
 *
 * `path` is relative to the install folder; use `getLaunchCandidatePaths()` to
 * resolve it.
 */
export interface IItchLaunchCandidate {
  path: string;
  /** File permission bits. */
  mode?: number;
  /** Number of path elements leading up to this candidate. */
  depth?: number;
  flavor?: IItchFlavor;
  arch?: IItchArch;
  size?: number;
  /** Raw output from itch's `wizardry` file-type detection. */
  spell?: string[];
  windowsInfo?: IItchWindowsInfo;
  linuxInfo?: IItchLinuxInfo;
  macosInfo?: IItchMacosInfo;
  loveInfo?: IItchLoveInfo;
  scriptInfo?: IItchScriptInfo;
  jarInfo?: IItchJarInfo;
  metadata?: Record<string, unknown>;
}

/** Butler's scan of an install folder, stored on the cave. */
export interface IItchVerdict {
  /** Absolute path of the folder that was configured. */
  basePath?: string;
  /** Size in bytes of the folder and everything under it. */
  totalSize?: number;
  candidates?: IItchLaunchCandidate[] | null;
}
